steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['test']
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: [ 'package' ]
#  - name: gcr.io/cloud-builders/docker
#    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gcp-demo:$SHORT_SHA', '.' ]
  images: ["gcr.io/$PROJECT_ID/gcp-demo:$SHORT_SHA"]