steps:
  - name: maven:3-jdk-11
    id: Test
    entrypoint: mvn
    args: ['test']
  - name: maven:3-jdk-11
    id: Package
    entrypoint: mvn
    args: [ 'package' ]
#  - name: 'gcr.io/cloud-builders/docker'
#    id: Build
#    args:
#      - 'build'
#      - '-t'
#      - 'gcr.io/$PROJECT_ID/gcp-demo:$SHORT_SHA'
#      - '.'
#  images: ["gcr.io/$PROJECT_ID/gcp-demo:$SHORT_SHA"]