"%dev":
  quarkus:
    datasource:
      db-kind: postgresql
      username: postgres
      password: password
      jdbc:
        url: jdbc:postgresql://34.89.221.132:5432/grass-db?stringtype=unspecified
#  container-image:
#    registry: docker.io
quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: password
    jdbc:
      url: jdbc:postgresql:///grass-db?cloudSqlInstance=web-apps-278418:europe-west3:myquark&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=password

  hibernate-orm:
    database:
      generation: none

  swagger-ui:
    always-include: true

  flyway:
    migrate-at-start: true
    baseline-on-migrate: true

  kubernetes:
    namespace: test-dev
    env:
      vars:
        quarkus-profile: dev
    replicas: 2
    service-type: LoadBalancer
    image-pull-policy: IfNotPresent
    config-map-volumes:
      my-volume:
        config-map-name: my-config-map
    mounts:
      my-volume:
        path: /opt/mymount

  container-image:
    registry: gcr.io
    group: web-apps-278418
    tag: 1.0.0-SNAPSHOT
#    build: true
#    push: true