quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: password
    jdbc:
      url: jdbc:postgresql://34.89.221.132:5432/grass-db?stringtype=unspecified

  hibernate-orm:
    database:
      generation: none

  swagger-ui:
     always-include: true

  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
